### PR TITLE
Remove quotes from the CSON keys as they aren't required

### PR DESCRIPTION
**Pull request by Victorystick**
* Enables nice highlighting
* Cleaner

Sadly, it breaks `git blame`... :cry:

### CODE REVIEW

**Comment by 50Wliu** [comment]
:-1: against this since all other grammars have quotes.  Are you interested though in applying this change to all of the other languages?

/cc @atom/feedback

**Comment by MaximSokolov** [comment]
I am ready to update language-javascript

**Comment by MaximSokolov** [comment]
In addition, CSON allows to remove `comment` properties:
```coffee
comment: '...'
```
```coffee
# ...
```
:art: :
```coffee
captures:
  1:
    name: '...'
  2:
    name: '...'
```
```coffee
captures:
  1: name: '...'
  2: name: '...'
```

**Comment by Victorystick** [comment]
I don't mind going through all `atom/language-*` packages if you want. Likely, all grammars have quotes since that's what the conversion from `.tmLanguage` generated, not because that's what people developing the grammars want. I imagine that developers will welcome the change.

@MaximSokolov I guess we could remove the `comment` properties regardless.

**Comment by lee-dohm** [comment]
I feel like if the problem is with the way the keys are highlighted, we should fix the highlighter, not change the text. I wouldn't change from using addition to multiplication in C++ because addition was highlighted in a way I didn't like ... I would fix the highlighter.

**Comment by Victorystick** [comment]
> I agree about the comments.

:simple_smile:

Changing the highlighter would be nice, but that doesn't address the cleanliness. Opinion?

**Comment by Victorystick** [comment]
I see atom/language-javascript#254 is also ongoing.

**Comment by MaximSokolov** [comment]
Do you have any objection?
Probably this requires rebasing after #67

**Comment by Victorystick** [comment]
Closing to keep the issue tracker clean. This doesn't seem likely to happen.

**Pull request closed without merging**
