### PR TITLE
Some grammer tweaks

### PR DESCRIPTION
**Pull request by svanharmelen**
I put every change in it's own commit to make it easy to judge and test the changes. Run `atom --dev` to verify all is well...

### CODE REVIEW

**Comment by 50Wliu** [comment]
Could you please add specs for these?

**Comment by svanharmelen** [comment]
@50Wliu sure! So are you OK to merge these if I added the specs?

**Comment by svanharmelen** [comment]
Or maybe I should ask that to @kevinsawicki? Would be nice to have some feedback, but will look at the specs (later today or tomorrow I guess) so the Travis build will be successful.

**Comment by 50Wliu** [comment]
Haha yeah I just help out a bit with issue management :wink:.

**Comment by kevinsawicki** [comment]
> So are you OK to merge these if I added the specs?

Yeah, specs would be great :+1: 

Also, if you could, before and after screenshots are also really helpful just to showcase the improvements. Since I don't do much go programming these would really help to illuminate the differences :flashlight: 

Thanks!

**Comment by svanharmelen** [comment]
Cool... Writing the specs as we speak, so they will be in within the hour or so (if I manage to stay focussed for more than 5 minutes that is :wink:)

As for the screenshots part, that's no problem of course! Just one question on what the purpose would be of those screenshots? Just for you to judge/understand the changes in this PR? Or are you thinking of something else?

**Comment by kevinsawicki** [comment]
> Just for you to judge/understand the changes in this PR?

Exactly this, it also makes this pull request easier to revisit in the future and know immediately what was changed without having to try and understand the pattern changes.

**Comment by svanharmelen** [comment]
Check... Coming up...

**Comment by svanharmelen** [comment]
So here goes...

This is before:
image

And this is after:
image

**Comment by kevinsawicki** [comment]
@joefitzgerald and @rubyist what do you think of the changes in https://github.com/atom/language-go/pull/36#issuecomment-88974378? everything look good?

**Comment by rubyist** [comment]
These look nice to me.

**Comment by kevinsawicki** [comment]
Thanks @rubyist :green_heart:

**Pull request merged**
