### PR TITLE
Fix escaped chars and print verbs in multiline quotes

### PR DESCRIPTION
**Pull request by svanharmelen**

### CODE REVIEW

**Comment by svanharmelen** [comment]
As for the details, again two screenshots...

Before:
image

After:
image

**Comment by mnquintana** [comment]
Would you mind adding a spec for this?

**Comment by svanharmelen** [comment]
@mnquintana of course, just added them...

**Comment by svanharmelen** [comment]
Closing this one for now as I noticed I didn't do this 100% according to the language spec... So will put in an updated version is a few...

**Pull request closed without merging**
