### PR TITLE
added tokenizing user defined types

### PR DESCRIPTION
**Pull request by kdar**
Taken from the sublime-text Go.tmLanguage

### CODE REVIEW

**Comment by svanharmelen** [comment]
This will indeed tokenise the user defined type name, but **only** on the line that actually defines the type. No other places in the code will be able to tokenise the type name as being a user defined type, which causes the type name to be tokenised differently (and so probably being highlighted differently as well) throughout a single source code file.

Personally I think that only makes things less clear, but maybe I miss some valuable insights here?

**Comment by kdar** [comment]
Well I considered that, and that's how it worked in gosublime/sublimetext, but it's what I got used to and a lot of syntaxes have support for colorizing entities. To do what you suggest, would seem to require some package that could run a program to spit out the Go AST and tokenize based on that.

**Comment by svanharmelen** [comment]
Indeed, but that would make the language-go package a completely different beast all together :wink:

Think the change is valid based on the language specs, but personally I'm not in favour of creating the inconsistent tokenizing resulting from this change...

**Comment by kdar** [comment]
That's fine.

**Comment by svanharmelen** [comment]
@kdar please note that I'm just a contributer discussing my point of few and not the maintainer of this repo. So if you disagree with my reasoning you should reopen your PR and let the maintainer give his opinion as well...

**Comment by Victorystick** [comment]
This is similar to the discussion about package names not being variables in #52; I think this is a valid change. It may not be a complete solution to the typing problem, but it is less wrong than marking types with `variable.go`, as they are currently. If the tests still pass, I think this should be merged.

The Go grammar is pretty clear about when types can appear, so I think it should be possible to mark types separately from identifiers. It doesn't seem like `entity.name.type.go` is restricted to type declarations. In situations like `var x type`, `func (x type) type` etc. we should be able to mark all occurrences of types (except the built-ins and keywords) with `entity.name.type.go`.

Would something like that be interesting?

**Pull request closed without merging**
