### PR TITLE
Add a comma to the regexp

### PR DESCRIPTION
**Pull request by svanharmelen**
When a comma is behind a closing brace, this should also match both the decrease patterns

### CODE REVIEW

**Comment by svanharmelen** [comment]
@kevinsawicki if you have a moment to review this one? It's a minor tweak to the indent patterns making it match closing braces that only have a comma behind them.

**Comment by svanharmelen** [comment]
@izuzak @50Wliu I noticed you guys merged #51 and #53 without also merging this PR. So is anything wrong with this (small and low impact) change?

I asked @kevinsawicki to review as I thought he was the only one that could merge in this repo. But if you guys can as well, then please have a look and if ok it would be great if you can also merge this one.

Thx!

**Comment by 50Wliu** [comment]
> So is anything wrong with this (small and low impact) change?

Would specs be able to catch the new behavior so that it doesn't regress?

**Comment by svanharmelen** [comment]
@50Wliu currently there are no specs in this package for the regexps. But it makes sense, so I'll see if I can whip up something...

**Comment by svanharmelen** [comment]
@50Wliu and with these tests I think we are the first (or at least one of the first) language packages to have a pretty nice test coverage of the indent patterns :smiley:

**Comment by joefitzgerald** [comment]
:shipit:

**Comment by 50Wliu** [comment]
:+1:

**Pull request merged**
